### ISSUE TITLE
Buttons in top-right covered by login notification

### ISSUE THREAD

**Issue by Huh** [Huh/PopR_MT#20]
Move the buttons or see if you can hide the signed in notification.

**Comment by Huh** [comment]
Login notification removed using: 

```css
/* Hide shiny disconnect div  */
.shiny-server-account {
  display: none;
}
```

A new issue was made on the discussion issue tracker to allow this to show in a new div.
